// Mass Effect 3 (2012) Luma HDR mod: UE3, 32-bit, DX9 -> D3D11 via dgVoodoo2 (2.87.3 or 2.81.3).

// No DEVELOPMENT auto-debugger MessageBox on DLL attach: invisible under borderless/fullscreen and it blocks the
// loader (ReShade times out the addon load -> error 1114). Same failure as ME1/ME2/BL2/TW2 under dgVoodoo.
#define DISABLE_AUTO_DEBUGGER 1

#define GAME_MASS_EFFECT_3 1

#define ENABLE_NGX 0 // NGX is x64-only and the game is 32-bit
#define ENABLE_FIDELITY_SK 0
#define GEOMETRY_SHADER_SUPPORT 0
// SMAA replaces the game's FXAA pass. Core auto-registers the 6 "SMAA ..." passes from Luma_SMAA_impl.hlsl.
#define ENABLE_SMAA 1
// The Luma HDR bloom pyramid replaces the game's bloom. Core auto-registers the "Bloom ..." passes from Luma_Bloom_impl.hlsl.
#define ENABLE_BLOOM 1
// FixImpossiblePerRTBlend re-issues draws: outside DEVELOPMENT only this define makes original_draw_dispatch_func non-null.
#define ENABLE_POST_DRAW_DISPATCH_CALLBACK 1

#include "..\..\Core\core.hpp"

// ---- The passes this mod acts on or logs, keyed on the pixel shader.
enum class Pass : uint8_t
{
   None,
   Uber,        // SFX uber post, any of its 64 cooked perms (see kPasses)
   UberHalfRes, // motion blur into the half-res buffer
   Fxaa,        // FXAA 3 console (reads luma from the uber's alpha) or one of the PC presets FXAA0..5
   Video,       // Bink YUV->RGB, byte-identical to ME2 2010 and BL2/TPS
   // Vanilla bloom, quarter res (962x542 at 4K). Bright pass on both sources: tap * saturate((max(rgb) - cb4[8].y) * 0.5).
   DofBloomGather,  // full-res DoF perms: DoF blur + bloom in one target, x0.25
   BloomDownsample, // half-res perms: bloom only, /16, alpha 0
   BloomFilter,     // separable 14-tap blur (weights cb4[11..24]), H then V; also blurs the gather's DoF
   GammaCorrection, // UE3 FGammaCorrectionPixelShader, after a gamma-less uber
};
static constexpr bool IsBloomSource(Pass pass)
{
   return pass == Pass::DofBloomGather || pass == Pass::BloomDownsample;
}

// Hashes per dgVoodoo build: 2.87.3 emits ps_5_0, 2.81.3 ps_4_0, so every hash differs. The uber rows are generated by
// _tools/dgv_hashgen (every GlobalShaderCache perm pushed through each dgVoodoo build); replacements bind by file name.
struct PassHashes
{
   uint32_t hash;
   uint32_t hash_v281;
   Pass pass;
   const char* name;
};
static constexpr PassHashes kPasses[] = {
   {0x685A43D9, 0xB73CA1C8, Pass::Uber, "UberLUTGrainLinear"},
   {0xB43CE257, 0xF9AB584B, Pass::Uber, "UberLUTHalfResGrainLinear"},
   {0xFF1B76A7, 0x12995E01, Pass::Uber, "UberLUTGrain"},
   {0xAB8576E8, 0xBFB153C6, Pass::Uber, "UberLUTHalfResGrain"},
   {0x8304A8B9, 0x995D24D4, Pass::Uber, "UberALUGrainLinear"},
   {0x9A7A1687, 0x1B8A43A9, Pass::Uber, "UberALUHalfResGrainLinear"},
   {0x84B6C2C3, 0x29C0C474, Pass::Uber, "UberALUGrain"},
   {0x48C63FB7, 0x44984EF4, Pass::Uber, "UberALUHalfResGrain"},
   {0x2E0BF574, 0x4416D7E9, Pass::Uber, "UberLUTLinear"},
   {0xFFCB6EFA, 0xE95894AB, Pass::Uber, "UberLUTHalfResLinear"},
   {0xAE84C59B, 0xC4030C3C, Pass::Uber, "UberLUT"},
   {0xACAD5CA0, 0xB5904CD4, Pass::Uber, "UberLUTHalfRes"},
   {0x42E3BDCB, 0x9CF84701, Pass::Uber, "UberALULinear"},
   {0x712A322E, 0x41D9BBC6, Pass::Uber, "UberALUHalfResLinear"},
   {0x5C735D6E, 0x17BEB437, Pass::Uber, "UberALU"},
   {0xE7A392EB, 0xF1AF9739, Pass::Uber, "UberALUHalfRes"},
   {0x0D069CDE, 0xFE185DDC, Pass::Uber, "UberLUTGrainNoVignetteLinear"},
   {0x6B3E6DF1, 0x5D71BD7C, Pass::Uber, "UberLUTHalfResGrainNoVignetteLinear"},
   {0x7EC7DA77, 0xF1E2CDA3, Pass::Uber, "UberLUTGrainNoVignette"},
   {0x5F32C624, 0x264DE4D7, Pass::Uber, "UberLUTHalfResGrainNoVignette"},
   {0x832346E1, 0x3936DE2C, Pass::Uber, "UberALUGrainNoVignetteLinear"},
   {0xE7589782, 0x6620C17F, Pass::Uber, "UberALUHalfResGrainNoVignetteLinear"},
   {0x9908698D, 0xE2AE6960, Pass::Uber, "UberALUGrainNoVignette"},
   {0xF9781752, 0x7A179F9B, Pass::Uber, "UberALUHalfResGrainNoVignette"},
   {0x35B0E08F, 0x5ED815AB, Pass::Uber, "UberLUTNoVignetteLinear"},
   {0xFFBC0BFD, 0x689F70FE, Pass::Uber, "UberLUTHalfResNoVignetteLinear"},
   {0x58937398, 0x863033F5, Pass::Uber, "UberLUTNoVignette"},
   {0x8EEECCBA, 0xD2B23DBD, Pass::Uber, "UberLUTHalfResNoVignette"},
   {0xCCE7042E, 0xB10AB7CC, Pass::Uber, "UberALUNoVignetteLinear"},
   {0xCBFD8F26, 0x9E9D3D00, Pass::Uber, "UberALUHalfResNoVignetteLinear"},
   {0x891BC0A7, 0x1EDA93CD, Pass::Uber, "UberALUNoVignette"},
   {0xFC4F41E9, 0xED39AC42, Pass::Uber, "UberALUHalfResNoVignette"},
   {0xA3180A2B, 0x73643789, Pass::Uber, "UberLUTNoFilmicGrainLinear"},
   {0xC14D576C, 0xDE379AD8, Pass::Uber, "UberLUTNoFilmicHalfResGrainLinear"},
   {0x7042D182, 0x3C24AC91, Pass::Uber, "UberLUTNoFilmicGrain"},
   {0x534BD49E, 0xEF38D6F9, Pass::Uber, "UberLUTNoFilmicHalfResGrain"},
   {0x4F0A97F0, 0xD0D6DCA7, Pass::Uber, "UberALUNoFilmicGrainLinear"},
   {0xE528B090, 0x716BBC5B, Pass::Uber, "UberALUNoFilmicHalfResGrainLinear"},
   {0x5BDA3568, 0x9CD8E5C9, Pass::Uber, "UberALUNoFilmicGrain"},
   {0x641D856A, 0x4D0F74EB, Pass::Uber, "UberALUNoFilmicHalfResGrain"},
   {0x48521F78, 0xF3C9AF3D, Pass::Uber, "UberLUTNoFilmicLinear"},
   {0x88129E7A, 0xFFC3CC9C, Pass::Uber, "UberLUTNoFilmicHalfResLinear"},
   {0xF9DA1778, 0xF7B1BAAF, Pass::Uber, "UberLUTNoFilmic"},
   {0xFF453DE0, 0x326B5A4B, Pass::Uber, "UberLUTNoFilmicHalfRes"},
   {0xD9DFFCF0, 0xD94C250B, Pass::Uber, "UberALUNoFilmicLinear"},
   {0x1FB52803, 0x3C46729F, Pass::Uber, "UberALUNoFilmicHalfResLinear"},
   {0x854C2156, 0xCA998A2E, Pass::Uber, "UberALUNoFilmic"},
   {0x6AA620CC, 0x0F65A786, Pass::Uber, "UberALUNoFilmicHalfRes"},
   {0x32F54ADD, 0x02CA1467, Pass::Uber, "UberLUTNoFilmicGrainNoVignetteLinear"},
   {0x5EB80ADB, 0x57DB96AF, Pass::Uber, "UberLUTNoFilmicHalfResGrainNoVignetteLinear"},
   {0xC28D9EB7, 0xAAA786F0, Pass::Uber, "UberLUTNoFilmicGrainNoVignette"},
   {0x8992691B, 0xBD23672B, Pass::Uber, "UberLUTNoFilmicHalfResGrainNoVignette"},
   {0x263DF1A4, 0xD3867479, Pass::Uber, "UberALUNoFilmicGrainNoVignetteLinear"},
   {0x6E16F780, 0xE448D8FE, Pass::Uber, "UberALUNoFilmicHalfResGrainNoVignetteLinear"},
   {0xC3C57DAE, 0x1596394C, Pass::Uber, "UberALUNoFilmicGrainNoVignette"},
   {0x3660392B, 0xEF1DB99D, Pass::Uber, "UberALUNoFilmicHalfResGrainNoVignette"},
   {0x9422EDD7, 0xAD7310EA, Pass::Uber, "UberLUTNoFilmicNoVignetteLinear"},
   {0xBE74FC64, 0x3FE52182, Pass::Uber, "UberLUTNoFilmicHalfResNoVignetteLinear"},
   {0x81307299, 0x4F3A79EA, Pass::Uber, "UberLUTNoFilmicNoVignette"},
   {0x3317A943, 0x8032AAE8, Pass::Uber, "UberLUTNoFilmicHalfResNoVignette"},
   {0x1D058044, 0x7CC4991E, Pass::Uber, "UberALUNoFilmicNoVignetteLinear"},
   {0xDD4B7CA8, 0xDB7D3959, Pass::Uber, "UberALUNoFilmicHalfResNoVignetteLinear"},
   {0x2C967E0F, 0x64D47B6F, Pass::Uber, "UberALUNoFilmicNoVignette"},
   {0x556A0DAC, 0x2737F8FB, Pass::Uber, "UberALUNoFilmicHalfResNoVignette"},
   {0x21D4387A, 0xC3686CF1, Pass::UberHalfRes, "UberHalfRes"},
   {0x243EAC75, 0x5507643B, Pass::Fxaa, "FXAA"},
   {0xA34DF8D3, 0x77869865, Pass::Fxaa, "FXAA0"},
   {0x9B4A78AC, 0xE23621B7, Pass::Fxaa, "FXAA1"},
   {0x21EF8426, 0x24D2B985, Pass::Fxaa, "FXAA2"},
   {0x6CAE3E4B, 0xD71C06F6, Pass::Fxaa, "FXAA3"},
   {0xE17F7245, 0x291994CC, Pass::Fxaa, "FXAA4"},
   {0xAB1A7309, 0x6738B3A1, Pass::Fxaa, "FXAA5"},
   {0xE41621CF, 0x7EBF990A, Pass::Video, "Bink Video"},
   {0x699E0C60, 0xE39C6616, Pass::DofBloomGather, "DoF+Bloom Gather"},
   {0xA8595DEF, 0x4812865E, Pass::DofBloomGather, "DoF+Bloom Gather 4-tap"},
   {0xC6215545, 0xF9A88A20, Pass::BloomDownsample, "Bloom Downsample"},
   {0x367ADFAB, 0x8B19200F, Pass::BloomFilter, "Bloom Filter"},
   {0x4F17DDD4, 0x016C392F, Pass::GammaCorrection, "Gamma Correction"},
};
static const PassHashes* FindPass(uint32_t ps_hash)
{
   for (const auto& entry : kPasses)
   {
      if (entry.hash == ps_hash || entry.hash_v281 == ps_hash)
         return &entry;
   }
   return nullptr;
}

#if DEVELOPMENT
// Uber perm axis, from the generated name.
static bool IsAluUber(const PassHashes& entry)
{
   return std::strncmp(entry.name, "UberALU", 7) == 0;
}
#endif

static bool g_hide_ui = false; // session-only, never persisted

#if ENABLE_BLOOM
// Uber bindings of the Luma bloom (Luma_ME3_Tonemap.hlsl): clear of every perm's t0..t5 / s0..s5 and of dgVoodoo's b3/b4.
static constexpr uint32_t kLumaBloomSlot = 6;     // t6 = core DrawBloom mip 0, s6 = linear sampler
static constexpr uint32_t kBloomSourceCBSlot = 5; // b5 = GPU copy of this frame's gather/downsample b4 (bloom scale)
// Pyramid sigmas in mip texels (resolution-independent), ME1 2007's.
static constexpr float g_bloom_sigmas[] = {1.5f, 2.f, 2.f, 2.f, 1.f, 0.5f};
#endif

#if ENABLE_SMAA
// User settings, persisted in the [Luma] config section (LoadConfigs).
static bool g_smaa_enable = true;
static bool g_smaa_predication = true;      // predicate SMAA on geometry, using the depth in the scene buffer's alpha
static float g_smaa_pred_tolerance = 0.02f; // plane deviation counted as a full edge, as a fraction of view depth
// RCAS on the SMAA output, opt-in at 0 (ME1/BL2/TW2 precedent). At 0 its intermediate is never allocated.
static float g_rcas_sharpness = 0.f;
#if DEVELOPMENT
static bool g_smaa_pred_debug = false;   // show the predication mask instead of the antialiased frame
static bool g_smaa_pred_measure = false; // one-shot: log the mask's coverage above 0.5 and percentiles
#endif
#endif

#if DEVELOPMENT
// ---- DEV diagnostics, all written to ReShade.log with the "[Luma] ME3" prefix:
//  - first draw of each tracked pass: RT0 and every bound SRV (format, size), so canvas upgrades are visible;
//  - any NEW pass on the shared uber VS (an uber perm or half-res pass not in the table), once per hash;
//  - the first draw that writes a swapchain back buffer (the final copy), once;
//  - grade rows cb4[8..17] of the uber and bloom rows cb4[8..12] of the gather/downsample, read back 2 frames late
//    (never stalls), logged when they change;
//  - the bloom filter kernel (PS weights, VS offsets) of both directions, once;
//  - one-shot buttons: a synchronous cb4 dump of every uber/bloom draw of the next frame, and a whole-frame census.
// 2.87.3 hashes first, then their 2.81.3 twins.
static constexpr uint32_t kUberVSHashes[] = {0xD5392793, 0x7D3B6E34}; // shared by every uber perm and the half-res pass

// Scaleform GFx: the vertex shaders seen drawing the HUD. Luma replaces all 15 GFx PS in the global cache (alpha clamp,
// see Shaders/Mass Effect 3/Includes/GFxUI.hlsl), so a GFx draw whose PS is NOT replaced is a shader from elsewhere
// whose alpha may still extrapolate on the fp16 canvas: logged once.
// 2.81.3 has no twin for 0xD1DAADAD yet (both nearest candidates differ in position/colour layout).
static constexpr uint32_t kGFxVSHashes[] = {0x58070CDD, 0xD1DAADAD, 0x62901726, 0x771320A7, 0xE394AE9D, 0xD39B42CA, 0x26A9918F, 0x525AFAAF, 0xDCB6ABB9};

// dgVoodoo's PS constants c<N> sit at cb4[N+8]: every row the passes below read starts there.
static constexpr uint32_t kCB4FirstRow = 8;
static constexpr uint32_t kGradeRowCount = 10; // cb4[8..17]: every row any uber perm reads
// cb4[8..12]: 8 = (bloom scale, bright-pass threshold) on both sources; the gather also reads 10 (MinZ_MaxZRatio),
// 11 (DoF focus, 1/range, falloff) and 12 (max blur near, far).
static constexpr uint32_t kBloomRowCount = 5;
static constexpr uint32_t kFilterRowCount = 17;    // cb4[8..24]: 8 = UV clamp rect, 11..24 = the 14 tap weights
static constexpr uint32_t kFilterVSRowCount = 32;  // VS cb4[0..31]: the tap offsets live somewhere in here
static constexpr uint32_t kLogIntervalFrames = 30; // a fade changes the rows every frame; log it at most this often

static bool g_track_cb_rows = true;
static bool g_dump_cb = false;   // one-shot, synchronous: every uber/bloom draw of the next frame
static bool g_log_frame = false; // one-shot, from the first uber-VS draw to present

// Deferred cb4 readback of one pass family: one copy per frame at its first draw, mapped kSlots - 1 frames later
// (never stalls), logged when the pass or a row changed.
struct CB4Tracker
{
   static constexpr uint32_t kSlots = 3;
   static constexpr uint32_t kMaxRows = (std::max)(kGradeRowCount, kBloomRowCount);
   uint32_t row_count; // rows from kCB4FirstRow
   ComPtr<ID3D11Buffer> ring[kSlots];
   uint32_t ring_hash[kSlots] = {};
   uint32_t bytes = 0;
   uint32_t writes = 0;
   bool copied_this_frame = false;
   uint32_t logged_hash = 0;
   uint32_t logged_frame = 0;
   float logged_rows[kMaxRows][4] = {};
};
#endif

struct MassEffect3GameDeviceData final : public GameDeviceData
{
#if DEVELOPMENT
   bool pass_logged[std::size(kPasses)] = {};
   std::unordered_set<uint32_t> new_uber_vs_passes_logged;
   std::unordered_set<uint32_t> new_gfx_passes_logged;
   bool swapchain_writer_logged = false;
   bool frame_log_active = false;
   uint32_t frame_log_draws = 0;
   uint32_t frame_index = 0;

   CB4Tracker grade_rows{kGradeRowCount};
   CB4Tracker bloom_rows{kBloomRowCount};
   bool dump_cb_this_frame = false; // armed at present by g_dump_cb
   uint32_t filter_dumps = 0;       // H and V of the first filtered frame
   bool smaa_logged = false;
   bool bloom_logged = false;
#endif

   // Repaired blend states (FixImpossiblePerRTBlend), keyed by the ORIGINAL desc so a released state leaves no stale key.
   struct BlendDescCompare
   {
      bool operator()(const D3D11_BLEND_DESC& a, const D3D11_BLEND_DESC& b) const
      {
         return memcmp(&a, &b, sizeof(D3D11_BLEND_DESC)) < 0;
      }
   };
   std::map<D3D11_BLEND_DESC, ComPtr<ID3D11BlendState>, BlendDescCompare> fixed_blend_states;

   // The uber's fp16 scene (device Z in alpha), captured at its draw: the Luma bloom's source and SMAA predication's.
   // Reset every present.
   ComPtr<ID3D11ShaderResourceView> srv_scene;
   // The final canvas, from FXAA's render target: everything drawn to it after FXAA is the HUD (Hide Gameplay UI).
   // Reset every present, so a resize or a mirror swap never outlives a frame.
   ComPtr<ID3D11Resource> canvas_res;

#if ENABLE_BLOOM
   // GPU copy of this frame's bloom source b4 (gather or downsample), bound to the uber at b5 for its row 8.x, the
   // engine's per-volume bloom scale: same-frame, no CPU readback. Not copied this frame -> b5 null -> no bloom.
   ComPtr<ID3D11Buffer> cb_bloom_source_copy;
   bool bloom_source_copied = false;
   bool bloom_drawn_this_frame = false;
   // Core's DrawBloom mip 0 (core-managed; this is an AddRef'd view). Rebuilt every frame.
   ComPtr<ID3D11ShaderResourceView> srv_luma_bloom;
#endif

#if ENABLE_SMAA
   // Captured at the uber draw for SMAA predication: a GPU copy of the uber's own b4, whose MinZ_MaxZRatio row the
   // depth-extract CS needs to decode srv_scene's Z.
   ComPtr<ID3D11Buffer> cb_uber_copy;
   bool uber_constants_copied = false;

   // ---- SMAA (ME1 2007 shape, see RunSMAA) ----
   // Canvas size every resource below (and core's DrawSMAA intermediates) was created for. A change releases them all.
   uint32_t smaa_w = 0, smaa_h = 0;
   ComPtr<ID3D11Buffer> cb_smaa_metrics; // b1: (1/w, 1/h, w, h) + (predication scale, 0, 0, 0)
   float smaa_metrics_pred_scale = -1.f;
   // Linear-light decode of the FXAA input, for the neighborhood blend. The gamma input itself is read in place: unlike
   // ME1 the source (FXAA's t0) and the destination (its render target) are different canvases, so no snapshot is needed.
   ComPtr<ID3D11Texture2D> tex_input_linear;
   ComPtr<ID3D11UnorderedAccessView> uav_input_linear;
   ComPtr<ID3D11ShaderResourceView> srv_input_linear;

   // Predication: srv_scene's depth turned into an edge-ness mask by the depth-extract CS.
   ComPtr<ID3D11Buffer> cb_pred;
   float pred_tolerance = -1.f;
   ComPtr<ID3D11Texture2D> tex_pred;
   ComPtr<ID3D11UnorderedAccessView> uav_pred;
   ComPtr<ID3D11ShaderResourceView> srv_pred;

   void ReleasePredicationScratch()
   {
      uav_pred.reset();
      srv_pred.reset();
      tex_pred.reset();
   }

   // RCAS. The intermediate exists ONLY while sharpening is on: at 0 the last SMAA pass writes the canvas directly.
   ComPtr<ID3D11Buffer> cb_sharpen;
   float sharpen_amount = -1.f;
   ComPtr<ID3D11Texture2D> tex_smaa_out;
   ComPtr<ID3D11RenderTargetView> tex_smaa_out_rtv;
   ComPtr<ID3D11ShaderResourceView> tex_smaa_out_srv;

   void ReleaseSharpenScratch()
   {
      tex_smaa_out_rtv.reset();
      tex_smaa_out_srv.reset();
      tex_smaa_out.reset();
   }

   // Turning the feature off gives the address space back (32-bit process).
   void ReleaseSMAAScratch()
   {
      uav_input_linear.reset();
      srv_input_linear.reset();
      tex_input_linear.reset();
      ReleasePredicationScratch();
      ReleaseSharpenScratch();
   }
#endif
};

class MassEffect3Game final : public Game
{
   static MassEffect3GameDeviceData& GetGameDeviceData(DeviceData& device_data)
   {
      return *static_cast<MassEffect3GameDeviceData*>(device_data.game);
   }

   // One grade slider: config key, label, tooltip, range. The dirty flag re-uploads the settings cbuffer.
   static void DrawGradeSlider(DeviceData& device_data, float* value, float default_value, const char* key, const char* label, const char* tooltip, float max_value)
   {
      if (ImGui::SliderFloat(label, value, 0.f, max_value))
      {
         reshade::set_config_value(nullptr, NAME, key, *value);
         device_data.cb_luma_global_settings_dirty = true;
      }
      if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled)) // Bloom greys its sliders out
         ImGui::SetTooltip("%s", tooltip);
      if (DrawResetButton(*value, default_value, key))
         device_data.cb_luma_global_settings_dirty = true;
   }

   // Look injected shaders up with find(): operator[] default-inserts on a miss, mutating a map core's draw helpers read.
   template <typename ShaderMap>
   static auto FindShader(const ShaderMap& shaders, uint32_t name)
   {
      const auto it = shaders.find(name);
      return it != shaders.end() ? it->second.get() : nullptr;
   }
   template <typename ShaderMap>
   static bool AllShadersReady(const ShaderMap& shaders, std::initializer_list<uint32_t> names)
   {
      for (const uint32_t name : names)
      {
         if (FindShader(shaders, name) == nullptr)
            return false;
      }
      return true;
   }

   // GPU copy of the bound PS b4 (dgVoodoo's constant mirror) into a private cbuffer, recreated on a size change: the
   // pass's constants for a later pass of the same frame, no stall.
   static bool CopyBoundPSConstants(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, ComPtr<ID3D11Buffer>* copy)
   {
      ComPtr<ID3D11Buffer> cb;
      native_device_context->PSGetConstantBuffers(4, 1, cb.put());
      if (!cb)
         return false;
      D3D11_BUFFER_DESC bd = {};
      cb->GetDesc(&bd);
      D3D11_BUFFER_DESC copy_bd = {};
      if (*copy)
         (*copy)->GetDesc(&copy_bd);
      if (!*copy || copy_bd.ByteWidth != bd.ByteWidth)
      {
         copy->reset();
         copy_bd = {};
         copy_bd.ByteWidth = bd.ByteWidth;
         copy_bd.Usage = D3D11_USAGE_DEFAULT;
         copy_bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
         if (FAILED(native_device->CreateBuffer(&copy_bd, nullptr, copy->put())))
            return false;
      }
      native_device_context->CopyResource(copy->get(), cb.get());
      return true;
   }

   // dgVoodoo leaves blending ON for a secondary RT with RT0 off; D3D9 has one global state (TW2 water 0xDA16C815).
   // Ported verbatim from ME1 2007: repairs "RT0 off, RTn on" by giving the bound secondaries RT0's blend.
   static bool FixImpossiblePerRTBlend(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, MassEffect3GameDeviceData& gd, reshade::api::shader_stage stages, const ShaderHashesList<OneShaderPerPipeline>& original_shader_hashes, bool is_custom_pass, std::function<void()>* original_draw_dispatch_func)
   {
      // Luma's own passes never reach here (OnDrawOrDispatch's gate), so is_custom_pass skips the draws Luma replaced
      // (ME1 kept the same check). Without the dispatch func the draw cannot be re-issued.
      if (is_custom_pass || (stages & reshade::api::shader_stage::pixel) == 0 || original_draw_dispatch_func == nullptr)
         return false;

      ComPtr<ID3D11BlendState> blend_state;
      FLOAT blend_factor[4];
      UINT sample_mask = 0;
      native_device_context->OMGetBlendState(blend_state.put(), blend_factor, &sample_mask);
      if (!blend_state)
         return false; // no state object = default (blending off everywhere)

      D3D11_BLEND_DESC bd;
      blend_state->GetDesc(&bd);
      if (!bd.IndependentBlendEnable)
         return false; // one state for all targets: already D3D9-shaped

      const bool rt0_blending = bd.RenderTarget[0].BlendEnable != FALSE;
#if !DEVELOPMENT
      // Only "RT0 off, RTn on" is repaired, so outside DEVELOPMENT a blending RT0 skips the scan and the RT query.
      if (rt0_blending)
         return false;
#endif

      // Only BOUND targets count: stale BlendEnable in unused slots would match nearly every single-target draw.
      bool disagreement = false;
      for (UINT i = 1; i < D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT && !disagreement; i++)
         disagreement = bd.RenderTarget[i].BlendEnable != bd.RenderTarget[0].BlendEnable;
      if (!disagreement)
         return false;

      // RT0's blend bit is loop-invariant, so the two shapes are mutually exclusive: one flag out of the loop.
      ID3D11RenderTargetView* rtvs[D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT] = {};
      native_device_context->OMGetRenderTargets(D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT, rtvs, nullptr);
      bool bound_disagreement = false;
      for (UINT i = 0; i < D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT; i++)
      {
         if (rtvs[i] == nullptr)
            continue;
         bound_disagreement |= i > 0 && bd.RenderTarget[i].BlendEnable != bd.RenderTarget[0].BlendEnable;
         rtvs[i]->Release(); // references handed back; only bound/not-bound matters
      }
      const bool needs_fix = bound_disagreement && !rt0_blending;
      [[maybe_unused]] const bool inverse_shape = bound_disagreement && rt0_blending;

#if DEVELOPMENT
      // One line per distinct shader. Locked: this function runs on every context, so two can reach the set.
      if (needs_fix || inverse_shape)
      {
         static std::mutex logged_shaders_mutex;
         static std::unordered_set<uint64_t> logged_shaders;
         const uint64_t pixel_shader_hash = original_shader_hashes.pixel_shaders[0];
         const std::scoped_lock logged_shaders_lock(logged_shaders_mutex);
         if (logged_shaders.emplace(pixel_shader_hash).second)
         {
            reshade::log::message(reshade::log::level::warning,
               std::format("[ME3-BlendFix] impossible per-RT blend state (dgVoodoo artefact) on pixel shader 0x{:X} - {}", pixel_shader_hash, needs_fix ? "repaired" : "inverse shape, left alone").c_str());
         }
      }
#endif

      if (!needs_fix)
         return false;

      ComPtr<ID3D11BlendState> fixed_state;
      if (const auto it = gd.fixed_blend_states.find(bd); it != gd.fixed_blend_states.end())
      {
         fixed_state = it->second;
      }
      else
      {
         D3D11_BLEND_DESC fixed_desc = bd;
         for (UINT i = 1; i < D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT; i++)
         {
            if (fixed_desc.RenderTarget[i].BlendEnable == bd.RenderTarget[0].BlendEnable)
               continue;
            const UINT8 write_mask = fixed_desc.RenderTarget[i].RenderTargetWriteMask; // legal per-RT in D3D9, keep it
            fixed_desc.RenderTarget[i] = bd.RenderTarget[0];
            fixed_desc.RenderTarget[i].RenderTargetWriteMask = write_mask;
         }
         if (FAILED(native_device->CreateBlendState(&fixed_desc, fixed_state.put())) || !fixed_state)
            return false; // leave the draw untouched rather than run it half-applied
         gd.fixed_blend_states[bd] = fixed_state;
      }

      native_device_context->OMSetBlendState(fixed_state.get(), blend_factor, sample_mask);
      (*original_draw_dispatch_func)();
      native_device_context->OMSetBlendState(blend_state.get(), blend_factor, sample_mask); // hand the game back its own state
      return true;
   }

#if ENABLE_SMAA
   static bool CreateImmutableCB(ID3D11Device* device, const void* data, UINT size, ComPtr<ID3D11Buffer>& out)
   {
      out.reset();
      D3D11_BUFFER_DESC bd = {};
      bd.ByteWidth = size;
      bd.Usage = D3D11_USAGE_IMMUTABLE;
      bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
      D3D11_SUBRESOURCE_DATA sd = {};
      sd.pSysMem = data;
      return SUCCEEDED(device->CreateBuffer(&bd, &sd, out.put()));
   }

   // Typed format: the canvases start as r8g8b8a8_typeless, and a typeless texture cannot back an SRV/RTV (ME2's fix).
   static bool CreateDefaultTex(ID3D11Device* device, uint32_t w, uint32_t h, UINT bind_flags, ComPtr<ID3D11Texture2D>& out, DXGI_FORMAT format)
   {
      out.reset();
      D3D11_TEXTURE2D_DESC td = {};
      td.Width = w;
      td.Height = h;
      td.MipLevels = 1;
      td.ArraySize = 1;
      td.Format = (DXGI_FORMAT)reshade::api::format_to_default_typed((reshade::api::format)format);
      td.SampleDesc.Count = 1;
      td.Usage = D3D11_USAGE_DEFAULT;
      td.BindFlags = bind_flags;
      return SUCCEEDED(device->CreateTexture2D(&td, nullptr, out.put()));
   }

   // Core's DrawSMAA intermediates, dropped only on swapchain init. Views hold references: release all.
   static void ReleaseCoreSMAAIntermediates(DeviceData& device_data)
   {
      auto& mr = device_data.managed_resources;
      mr.depth_stencil_views[CompileTimeStringHash("smaa_dsv")].reset();
      mr.render_target_views[CompileTimeStringHash("smaa_edge_detection")].reset();
      mr.render_target_views[CompileTimeStringHash("smaa_blending_weight_calculation")].reset();
      mr.shader_resource_views[CompileTimeStringHash("smaa_edge_detection")].reset();
      mr.shader_resource_views[CompileTimeStringHash("smaa_blending_weight_calculation")].reset();
   }

#if DEVELOPMENT
   // Calibration readback (MoHA/ME1 method): coverage above 0.5 = geometry fraction, typically ~1%. One-shot; stalls.
   static void MeasurePredicationMask(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, ID3D11Texture2D* pred)
   {
      D3D11_TEXTURE2D_DESC td;
      pred->GetDesc(&td);
      td.Usage = D3D11_USAGE_STAGING;
      td.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
      td.BindFlags = 0;
      td.MiscFlags = 0;
      ComPtr<ID3D11Texture2D> staging;
      if (FAILED(native_device->CreateTexture2D(&td, nullptr, staging.put())))
         return;
      native_device_context->CopyResource(staging.get(), pred);
      D3D11_MAPPED_SUBRESOURCE mapped = {};
      if (FAILED(native_device_context->Map(staging.get(), 0, D3D11_MAP_READ, 0, &mapped)) || mapped.pData == nullptr)
         return;

      constexpr int kBuckets = 1024;
      std::vector<uint64_t> histogram(kBuckets, 0);
      uint64_t total = 0, above_half = 0, nans = 0;
      double sum = 0.0;
      for (uint32_t y = 0; y < td.Height; y++)
      {
         const uint16_t* row = reinterpret_cast<const uint16_t*>(static_cast<const uint8_t*>(mapped.pData) + (size_t)y * mapped.RowPitch);
         for (uint32_t x = 0; x < td.Width; x++)
         {
            const float v = DirectX::PackedVector::XMConvertHalfToFloat(row[x]);
            if (std::isnan(v))
            {
               nans++;
               continue;
            }
            total++;
            sum += v;
            if (v > 0.5f)
               above_half++;
            histogram[std::clamp((int)(v * kBuckets), 0, kBuckets - 1)]++;
         }
      }
      native_device_context->Unmap(staging.get(), 0);
      if (total == 0)
         return;

      auto percentile = [&](double fraction)
      {
         const uint64_t target = (uint64_t)(fraction * (double)total);
         uint64_t running = 0;
         for (int i = 0; i < kBuckets; i++)
         {
            running += histogram[i];
            if (running >= target)
               return (float)(i + 1) / (float)kBuckets;
         }
         return 1.f;
      };
      char msg[512];
      std::snprintf(msg, sizeof(msg), "[Luma] ME3: SMAA predication mask %ux%u tolerance %.4f -> above 0.5 = %.2f%% | mean %.4f | p50 %.4f p90 %.4f p99 %.4f | NaN %llu",
         td.Width, td.Height, g_smaa_pred_tolerance, 100.0 * (double)above_half / (double)total, sum / (double)total, percentile(0.50), percentile(0.90), percentile(0.99), (unsigned long long)nans);
      reshade::log::message(reshade::log::level::info, msg);
   }
#endif

   // SMAA in place of FXAA (ME1 chain): gamma input (FXAA's t0) -> linear decode -> [predication] -> DrawSMAA -> [RCAS]
   // -> FXAA's render target. False when anything is not ready, so the caller lets the game's FXAA run instead.
   bool RunSMAA(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, DeviceData& device_data, MassEffect3GameDeviceData& gd, ID3D11ShaderResourceView* input_srv, ID3D11RenderTargetView* canvas_rtv)
   {
      uint4 cinfo{};
      DXGI_FORMAT cfmt = DXGI_FORMAT_UNKNOWN;
      GetResourceInfo(canvas_rtv, cinfo, cfmt);
      const uint32_t w = cinfo.x, h = cinfo.y;
      if (w == 0 || h == 0 || cfmt == DXGI_FORMAT_UNKNOWN)
         return false;

      // Shader-readiness gate (async loader / dev live-reload).
      auto* linearize_cs = FindShader(device_data.native_compute_shaders, CompileTimeStringHash("ME3 SMAA Linearize CS"));
      if (linearize_cs == nullptr || !AllShadersReady(device_data.native_pixel_shaders, {CompileTimeStringHash("SMAA Edge Detection PS"), CompileTimeStringHash("SMAA Blending Weight Calculation PS"), CompileTimeStringHash("SMAA Neighborhood Blending PS")}) || !AllShadersReady(device_data.native_vertex_shaders, {CompileTimeStringHash("SMAA Edge Detection VS"), CompileTimeStringHash("SMAA Blending Weight Calculation VS"), CompileTimeStringHash("SMAA Neighborhood Blending VS")}))
         return false;

      // Resolution change: drop every size-bound resource, ours and DrawSMAA's core-managed intermediates.
      if (gd.smaa_w != w || gd.smaa_h != h)
      {
         gd.ReleaseSMAAScratch();
         gd.cb_smaa_metrics.reset();
         gd.cb_sharpen.reset();
         ReleaseCoreSMAAIntermediates(device_data);
         gd.smaa_w = w;
         gd.smaa_h = h;
      }

      // Scale and mask fall back together: 2.0 with a null mask would raise the threshold frame-wide. CS maps texels 1:1.
      auto* pred_cs = FindShader(device_data.native_compute_shaders, CompileTimeStringHash("ME3 Depth Extract CS"));
      bool pred_ok = g_smaa_predication && gd.srv_scene.get() != nullptr && gd.uber_constants_copied && pred_cs != nullptr;
      if (pred_ok)
      {
         uint4 sinfo{};
         DXGI_FORMAT sfmt = DXGI_FORMAT_UNKNOWN;
         GetResourceInfo(gd.srv_scene.get(), sinfo, sfmt);
         pred_ok = sinfo.x == w && sinfo.y == h;
      }
      if (pred_ok)
      {
         if (!gd.cb_pred || gd.pred_tolerance != g_smaa_pred_tolerance)
         {
            const float p[4] = {g_smaa_pred_tolerance, 0.f, 0.f, 0.f};
            if (CreateImmutableCB(native_device, p, sizeof(p), gd.cb_pred))
               gd.pred_tolerance = g_smaa_pred_tolerance;
         }
         if (!gd.uav_pred || !gd.srv_pred)
         {
            gd.ReleasePredicationScratch();
            if (CreateDefaultTex(native_device, w, h, D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_UNORDERED_ACCESS, gd.tex_pred, DXGI_FORMAT_R16_FLOAT))
            {
               native_device->CreateUnorderedAccessView(gd.tex_pred.get(), nullptr, gd.uav_pred.put());
               native_device->CreateShaderResourceView(gd.tex_pred.get(), nullptr, gd.srv_pred.put());
            }
         }
         pred_ok = gd.cb_pred && gd.uav_pred && gd.srv_pred;
      }

      const float pred_scale = pred_ok ? 2.f : 1.f;
      if (!gd.cb_smaa_metrics || gd.smaa_metrics_pred_scale != pred_scale)
      {
         const float metrics[8] = {1.f / (float)w, 1.f / (float)h, (float)w, (float)h, pred_scale, 0.f, 0.f, 0.f};
         if (CreateImmutableCB(native_device, metrics, sizeof(metrics), gd.cb_smaa_metrics))
            gd.smaa_metrics_pred_scale = pred_scale;
      }
      if (!gd.cb_smaa_metrics)
         return false;

      // RCAS decides the chain's SHAPE: with sharpening off the last SMAA pass writes the canvas directly.
      auto* copy_vs = FindShader(device_data.native_vertex_shaders, CompileTimeStringHash("Copy VS"));
      auto* sharpen_ps = FindShader(device_data.native_pixel_shaders, CompileTimeStringHash("ME3 Sharpen PS"));
      bool do_sharpen = g_rcas_sharpness > 0.f && copy_vs != nullptr && sharpen_ps != nullptr;
      if (do_sharpen)
      {
         if (!gd.cb_sharpen || gd.sharpen_amount != g_rcas_sharpness)
         {
            const float sp[4] = {(float)w, (float)h, g_rcas_sharpness, 0.f};
            if (CreateImmutableCB(native_device, sp, sizeof(sp), gd.cb_sharpen))
               gd.sharpen_amount = g_rcas_sharpness;
         }
         if (!gd.tex_smaa_out_rtv || !gd.tex_smaa_out_srv)
         {
            gd.ReleaseSharpenScratch();
            if (CreateDefaultTex(native_device, w, h, D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET, gd.tex_smaa_out, cfmt))
            {
               native_device->CreateRenderTargetView(gd.tex_smaa_out.get(), nullptr, gd.tex_smaa_out_rtv.put());
               native_device->CreateShaderResourceView(gd.tex_smaa_out.get(), nullptr, gd.tex_smaa_out_srv.put());
            }
         }
         if (!gd.cb_sharpen || !gd.tex_smaa_out_rtv || !gd.tex_smaa_out_srv)
            do_sharpen = false; // allocation failed: fall back to the un-sharpened chain rather than dropping SMAA
      }

      if (!gd.uav_input_linear || !gd.srv_input_linear)
      {
         gd.uav_input_linear.reset();
         gd.srv_input_linear.reset();
         if (CreateDefaultTex(native_device, w, h, D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_UNORDERED_ACCESS, gd.tex_input_linear, DXGI_FORMAT_R16G16B16A16_FLOAT))
         {
            native_device->CreateUnorderedAccessView(gd.tex_input_linear.get(), nullptr, gd.uav_input_linear.put());
            native_device->CreateShaderResourceView(gd.tex_input_linear.get(), nullptr, gd.srv_input_linear.put());
         }
      }
      if (!gd.uav_input_linear || !gd.srv_input_linear)
         return false;

#if DEVELOPMENT
      if (!gd.smaa_logged)
      {
         gd.smaa_logged = true;
         char msg[256];
         std::snprintf(msg, sizeof(msg), "[Luma] ME3: SMAA first run: input %s -> canvas %s, predication %s", DescribeView(input_srv).c_str(), DescribeView(canvas_rtv).c_str(), pred_ok ? "on" : "off");
         LogLine(msg);
      }
#endif

      // Linear-light decode of the input for the neighborhood blend (Luma_ME3_SMAALinearize.hlsl).
      {
         DrawStateStack<DrawStateStackType::Compute> linearize_state;
         linearize_state.Cache(native_device_context, device_data.uav_max_count);
         ID3D11UnorderedAccessView* lin_uav = gd.uav_input_linear.get();
         native_device_context->CSSetUnorderedAccessViews(0, 1, &lin_uav, nullptr);
         native_device_context->CSSetShaderResources(0, 1, &input_srv);
         native_device_context->CSSetShader(linearize_cs, nullptr, 0);
         native_device_context->Dispatch((w + 7) / 8, (h + 7) / 8, 1);
         linearize_state.Restore(native_device_context);
      }

      // Scene device Z -> view depth -> plane-deviation edge-ness (R16F); see Luma_ME3_DepthExtract.hlsl.
      if (pred_ok)
      {
         DrawStateStack<DrawStateStackType::Compute> pred_cs_state;
         pred_cs_state.Cache(native_device_context, device_data.uav_max_count);
         ID3D11ShaderResourceView* pred_srv = gd.srv_scene.get();
         ID3D11UnorderedAccessView* pred_uav = gd.uav_pred.get();
         ID3D11Buffer* pred_cbs[2] = {gd.cb_pred.get(), gd.cb_uber_copy.get()};
         native_device_context->CSSetShaderResources(0, 1, &pred_srv);
         native_device_context->CSSetUnorderedAccessViews(0, 1, &pred_uav, nullptr);
         native_device_context->CSSetConstantBuffers(0, 2, pred_cbs);
         native_device_context->CSSetShader(pred_cs, nullptr, 0);
         native_device_context->Dispatch((w + 7) / 8, (h + 7) / 8, 1);
         pred_cs_state.Restore(native_device_context);
      }

#if DEVELOPMENT
      if (g_smaa_pred_measure)
      {
         g_smaa_pred_measure = false;
         if (pred_ok)
            MeasurePredicationMask(native_device, native_device_context, gd.tex_pred.get());
         else
            LogLine("[Luma] ME3: SMAA predication mask not measured: predication inactive this frame (no scene capture, size mismatch or CS missing)");
      }
      if (pred_ok && g_smaa_pred_debug)
      {
         auto* copy_ps = FindShader(device_data.native_pixel_shaders, CompileTimeStringHash("Copy PS"));
         if (copy_vs != nullptr && copy_ps != nullptr)
         {
            // Single-channel, so the copy shows it in RED. It replaces the frame.
            DrawStateStack<DrawStateStackType::FullGraphics> debug_state;
            debug_state.Cache(native_device_context, device_data.uav_max_count);
            DrawCustomPixelShader(native_device_context, device_data.default_depth_stencil_state.get(), device_data.default_blend_state.get(), nullptr,
               copy_vs, copy_ps, gd.srv_pred.get(), canvas_rtv, w, h, false);
            debug_state.Restore(native_device_context);
            return true;
         }
      }
#endif

      // Metrics CB at VS+PS b1 (DrawSMAA restores VS/PS/SRVs/RTs, but not cbuffers).
      ComPtr<ID3D11Buffer> vs_cb1_orig, ps_cb1_orig;
      native_device_context->VSGetConstantBuffers(1, 1, vs_cb1_orig.put());
      native_device_context->PSGetConstantBuffers(1, 1, ps_cb1_orig.put());
      ID3D11Buffer* mcb = gd.cb_smaa_metrics.get();
      native_device_context->VSSetConstantBuffers(1, 1, &mcb);
      native_device_context->PSSetConstantBuffers(1, 1, &mcb);

      DrawSMAA(native_device, native_device_context, device_data, do_sharpen ? gd.tex_smaa_out_rtv.get() : canvas_rtv, gd.srv_input_linear.get(), input_srv, pred_ok ? gd.srv_pred.get() : nullptr);

      if (do_sharpen)
      {
         DrawStateStack<DrawStateStackType::FullGraphics> sharpen_state;
         sharpen_state.Cache(native_device_context, device_data.uav_max_count);
         ID3D11Buffer* scb = gd.cb_sharpen.get();
         native_device_context->PSSetConstantBuffers(0, 1, &scb);
         DrawCustomPixelShader(native_device_context, device_data.default_depth_stencil_state.get(), device_data.default_blend_state.get(), nullptr,
            copy_vs, sharpen_ps, gd.tex_smaa_out_srv.get(), canvas_rtv, w, h, false);
         sharpen_state.Restore(native_device_context);
      }

      ID3D11Buffer* vcb = vs_cb1_orig.get();
      ID3D11Buffer* pcb = ps_cb1_orig.get();
      native_device_context->VSSetConstantBuffers(1, 1, &vcb);
      native_device_context->PSSetConstantBuffers(1, 1, &pcb);
      return true;
   }
#endif // ENABLE_SMAA

public:
   void OnInit(bool async) override
   {
      // Shaders/Mass Effect 3/Luma_ME3_Tonemap.hlsl, shared by every uber perm replacement and GammaCorrection.
      std::vector<ShaderDefineData> game_shader_defines_data = {
         {"TONEMAP_TYPE", /*default value*/ '1', true, false, /*tooltip*/ "0 - Vanilla SDR\n1 - Luma HDR (Vanilla+)", /*max value*/ 1},
      };
      shader_defines_data.append_range(game_shader_defines_data);
      assert(shader_defines_data.size() < MAX_SHADER_DEFINES);

#if ENABLE_SMAA
      // Core auto-registers the 6 SMAA passes. Ours: the linear decode its blend reads, the predication CS turning the
      // scene's depth into R16F edge-ness, and the RCAS PS drawn via core "Copy VS".
      native_shaders_definitions.emplace(CompileTimeStringHash("ME3 SMAA Linearize CS"),
         ShaderDefinition("Luma_ME3_SMAALinearize", reshade::api::pipeline_subobject_type::compute_shader));
      native_shaders_definitions.emplace(CompileTimeStringHash("ME3 Depth Extract CS"),
         ShaderDefinition("Luma_ME3_DepthExtract", reshade::api::pipeline_subobject_type::compute_shader));
      native_shaders_definitions.emplace(CompileTimeStringHash("ME3 Sharpen PS"),
         ShaderDefinition{"Luma_ME3_Sharpen", reshade::api::pipeline_subobject_type::pixel_shader, nullptr, "sharpen_ps"});
#endif

      // Same encoding as ME1/ME2: gamma canvas (FXAA and the gamma GFx HUD run on it after the uber), plain power 2.2
      // (the uber's output exponent, cb4[12].w or cb4[16].w on ALU perms). Core's composition decodes and applies UI
      // Paper White at present.
      GetShaderDefineData(POST_PROCESS_SPACE_TYPE_HASH).SetDefaultValue('0');
      GetShaderDefineData(EARLY_DISPLAY_ENCODING_HASH).SetDefaultValue('0');
      GetShaderDefineData(VANILLA_ENCODING_TYPE_HASH).SetDefaultValue('1');
      GetShaderDefineData(GAMMA_CORRECTION_TYPE_HASH).SetDefaultValue('1');
      GetShaderDefineData(GAMUT_MAPPING_TYPE_HASH).SetDefaultValue('1');
      GetShaderDefineData(UI_DRAW_TYPE_HASH).SetDefaultValue('2'); // the uber pre-scales by Game/UI Paper White

      luma_settings_cbuffer_index = 13;
      luma_data_cbuffer_index = 12;
      luma_ui_cbuffer_index = -1;

      // Manual paper-white sliders, not the OS reference level. Core gates the UI one on UI_DRAW_TYPE >= 1.
      use_os_reference_white_level = false;

      // Must be set: the cbuffer starts zeroed, and Exposure 0 is a black screen.
      default_luma_global_game_settings.Exposure = 1.f;
      default_luma_global_game_settings.Saturation = 1.f;
      default_luma_global_game_settings.HighlightDechroma = 0.f;
      default_luma_global_game_settings.Contrast = 1.f;
      default_luma_global_game_settings.VignetteIntensity = 1.f;
      default_luma_global_game_settings.FilmGrainIntensity = 1.f;
      default_luma_global_game_settings.Dithering = 1.f;
      default_luma_global_game_settings.VideoAutoHDREnable = 1.f;
      default_luma_global_game_settings.VideoAutoHDRBoost = 0.5f;
      default_luma_global_game_settings.BloomIntensity = 1.f;
      default_luma_global_game_settings.LumaBloomEnable = ENABLE_BLOOM ? 1.f : 0.f;
      default_luma_global_game_settings.BloomThreshold = 1.f; // the game's bright-pass, cb4[8].y measured 1.0 everywhere
      cb_luma_global_settings.GameSettings = default_luma_global_game_settings;
   }

   void LoadConfigs() override
   {
      // cb_luma_global_settings_dirty is already true at init, so these reach the GPU on the first frame.
      auto& gs = cb_luma_global_settings.GameSettings;
      reshade::get_config_value(nullptr, NAME, "Exposure", gs.Exposure);
      reshade::get_config_value(nullptr, NAME, "Contrast", gs.Contrast);
      reshade::get_config_value(nullptr, NAME, "Saturation", gs.Saturation);
      reshade::get_config_value(nullptr, NAME, "HighlightsDesaturation", gs.HighlightDechroma);
      reshade::get_config_value(nullptr, NAME, "VignetteIntensity", gs.VignetteIntensity);
      reshade::get_config_value(nullptr, NAME, "FilmGrainIntensity", gs.FilmGrainIntensity);
      reshade::get_config_value(nullptr, NAME, "Dithering", gs.Dithering);
      reshade::get_config_value(nullptr, NAME, "VideoAutoHDREnable", gs.VideoAutoHDREnable);
      reshade::get_config_value(nullptr, NAME, "VideoAutoHDRBoost", gs.VideoAutoHDRBoost);
#if ENABLE_BLOOM
      reshade::get_config_value(nullptr, NAME, "LumaBloomEnable", gs.LumaBloomEnable);
      reshade::get_config_value(nullptr, NAME, "BloomIntensity", gs.BloomIntensity);
      reshade::get_config_value(nullptr, NAME, "BloomThreshold", gs.BloomThreshold);
#endif
#if ENABLE_SMAA
      // Plain globals rather than cbuffer fields: these drive the mod's own injected passes, not a shader setting.
      reshade::get_config_value(nullptr, NAME, "SMAAEnable", g_smaa_enable);
      reshade::get_config_value(nullptr, NAME, "SMAAPredication", g_smaa_predication);
      reshade::get_config_value(nullptr, NAME, "SMAAPredicationTolerance", g_smaa_pred_tolerance);
      reshade::get_config_value(nullptr, NAME, "RCASSharpness", g_rcas_sharpness);
#endif
   }

   void DrawImGuiSettings(DeviceData& device_data) override
   {
      auto& gs = cb_luma_global_settings.GameSettings;
      const auto& def = default_luma_global_game_settings;

#if ENABLE_SMAA
      // Nothing here touches cb_luma_global_settings, so no dirty flag: these drive Luma's own passes.
      ImGui::SeparatorText("Anti-Aliasing");
      if (ImGui::Checkbox("SMAA Enable", &g_smaa_enable))
         reshade::set_config_value(nullptr, NAME, "SMAAEnable", g_smaa_enable);
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Replaces the game's FXAA with SMAA (requires Anti-Aliasing enabled in the game's graphics settings).");
      if (g_smaa_enable)
      {
#if DEVELOPMENT
         if (ImGui::Checkbox("SMAA Predication", &g_smaa_predication))
            reshade::set_config_value(nullptr, NAME, "SMAAPredication", g_smaa_predication);
         if (ImGui::IsItemHovered())
            ImGui::SetTooltip("Finds edges by geometry (scene depth) instead of by brightness alone.\nKeeps textures sharp while still antialiasing real silhouettes.");
         if (ImGui::SliderFloat("SMAA Predication Tolerance", &g_smaa_pred_tolerance, 0.002f, 0.2f, "%.3f", ImGuiSliderFlags_Logarithmic))
            reshade::set_config_value(nullptr, NAME, "SMAAPredicationTolerance", g_smaa_pred_tolerance);
         if (ImGui::IsItemHovered())
            ImGui::SetTooltip("How far a surface may deviate from its local plane before it counts as an edge,\nas a fraction of view depth. Lower = more edges.");
         ImGui::Checkbox("SMAA Predication Debug View", &g_smaa_pred_debug);
         if (ImGui::IsItemHovered())
            ImGui::SetTooltip("Show the predication mask (red) instead of the frame.\nWant: black on flat surfaces, red across silhouettes.");
         if (ImGui::Button("Measure Predication Mask"))
            g_smaa_pred_measure = true;
         if (ImGui::IsItemHovered())
            ImGui::SetTooltip("Log the mask's coverage above 0.5 plus percentiles to ReShade.log. Stalls the GPU for one frame.");
#endif
         if (ImGui::SliderFloat("RCAS Sharpness", &g_rcas_sharpness, 0.f, 1.f))
            reshade::set_config_value(nullptr, NAME, "RCASSharpness", g_rcas_sharpness);
         if (ImGui::IsItemHovered())
            ImGui::SetTooltip("Sharpening applied on top of SMAA (0 = off).");
         DrawResetButton(g_rcas_sharpness, 0.f, "RCASSharpness");
      }
#endif

      ImGui::SeparatorText("Grade");
      DrawGradeSlider(device_data, &gs.Exposure, def.Exposure, "Exposure", "Exposure", "Overall image brightness (1 = vanilla).", 2.f);
      DrawGradeSlider(device_data, &gs.Contrast, def.Contrast, "Contrast", "Contrast", "Overall image contrast, HDR only (1 = vanilla).", 2.f);
      DrawGradeSlider(device_data, &gs.Saturation, def.Saturation, "Saturation", "Saturation", "Color saturation, HDR only (1 = vanilla).", 2.f);
      DrawGradeSlider(device_data, &gs.HighlightDechroma, def.HighlightDechroma, "HighlightsDesaturation", "Highlights Desaturation", "How far the brightest sources fade to neutral white, HDR only (0 = keep color at any brightness).", 1.f);

#if ENABLE_BLOOM
      ImGui::SeparatorText("Bloom");
      // One switch for the uber, the replaced gathers and the Luma pyramid pass: it swaps the blooms.
      bool luma_bloom = gs.LumaBloomEnable > 0.5f;
      if (ImGui::Checkbox("Luma Bloom Enable", &luma_bloom))
      {
         gs.LumaBloomEnable = luma_bloom ? 1.f : 0.f;
         reshade::set_config_value(nullptr, NAME, "LumaBloomEnable", gs.LumaBloomEnable);
         device_data.cb_luma_global_settings_dirty = true;
      }
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Replaces the game's bloom with a wider, softer HDR bloom.");
      // Everything below drives the Luma pyramid only and greys out with it.
      ImGui::BeginDisabled(!luma_bloom);
      DrawGradeSlider(device_data, &gs.BloomIntensity, def.BloomIntensity, "BloomIntensity", "Bloom Intensity", "Bloom strength (1 = vanilla, 0 = none).", 2.f);
#if DEVELOPMENT
      DrawGradeSlider(device_data, &gs.BloomThreshold, def.BloomThreshold, "BloomThreshold", "Bloom Threshold", "Linear scene brightness where bloom starts. 1.0 is where the game's own bright-pass sits.", 4.f);
#endif
      ImGui::EndDisabled();
#endif

      ImGui::SeparatorText("Effects");
      DrawGradeSlider(device_data, &gs.VignetteIntensity, def.VignetteIntensity, "VignetteIntensity", "Vignette Intensity", "Scales the game's vignette darkening (1 = vanilla, 0 = none).", 1.f);
      DrawGradeSlider(device_data, &gs.FilmGrainIntensity, def.FilmGrainIntensity, "FilmGrainIntensity", "Film Grain Intensity", "Scales the game's film grain (1 = vanilla, 0 = off).", 1.f);
      // Read in Video_0xE41621CF.ps_5_0.hlsl.
      bool video_auto_hdr = gs.VideoAutoHDREnable > 0.5f;
      if (ImGui::Checkbox("Video AutoHDR", &video_auto_hdr))
      {
         gs.VideoAutoHDREnable = video_auto_hdr ? 1.f : 0.f;
         reshade::set_config_value(nullptr, NAME, "VideoAutoHDREnable", gs.VideoAutoHDREnable);
         device_data.cb_luma_global_settings_dirty = true;
      }
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Adds HDR highlights to pre-rendered videos (HDR only).");
      ImGui::BeginDisabled(!video_auto_hdr);
      DrawGradeSlider(device_data, &gs.VideoAutoHDRBoost, def.VideoAutoHDRBoost, "VideoAutoHDRBoost", "Video HDR Boost", "Video highlight strength (0 = off).", 1.f);
      ImGui::EndDisabled();

      bool dithering = gs.Dithering > 0.5f;
      if (ImGui::Checkbox("Dithering", &dithering))
      {
         gs.Dithering = dithering ? 1.f : 0.f;
         reshade::set_config_value(nullptr, NAME, "Dithering", gs.Dithering);
         device_data.cb_luma_global_settings_dirty = true;
      }
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Reduces gradient banding.");

      ImGui::SeparatorText("UI");
      ImGui::Checkbox("Hide Gameplay UI", &g_hide_ui); // Session-only: a stuck "on" would look like a broken HUD.
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Disables the in-game UI.");

#if DEVELOPMENT
      ImGui::SeparatorText("Diagnostics");
      ImGui::Checkbox("Track Constants", &g_track_cb_rows);
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Log the uber's cb4[8..17] and the bloom source's cb4[8..12] to ReShade.log whenever they change (read 2 frames late, no stall).");
      if (ImGui::Button("Dump Frame Constants"))
         g_dump_cb = true;
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Log the constants and bindings of every uber and bloom draw of the next frame. Stalls the GPU.");
      ImGui::SameLine();
      if (ImGui::Button("Log One Frame"))
         g_log_frame = true;
      if (ImGui::IsItemHovered())
         ImGui::SetTooltip("Log every draw from the first uber-VS draw to present: shaders, RT0, t0.");
#endif
   }

   void OnCreateDevice(ID3D11Device* native_device, DeviceData& device_data) override
   {
      device_data.game = new MassEffect3GameDeviceData;
   }

#if DEVELOPMENT
   static const char* PassName(uint32_t ps_hash)
   {
      const PassHashes* entry = FindPass(ps_hash);
      return entry ? entry->name : "unknown";
   }

   static void LogLine(const char* msg)
   {
      reshade::log::message(reshade::log::level::info, msg);
   }

   // "fmt WxH" of a view's resource, or "-" when null. Resource formats: an indirectly upgraded canvas shows fp16 here.
   static std::string DescribeView(ID3D11View* view)
   {
      if (!view)
         return "-";
      uint4 size{};
      DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN;
      GetResourceInfo(view, size, format);
      char text[96];
      std::snprintf(text, sizeof(text), "%s %ux%u", GetFormatNameSafe(format), size.x, size.y);
      return text;
   }

   static bool IsBackBuffer(DeviceData& device_data, ID3D11View* view)
   {
      if (!view)
         return false;
      ComPtr<ID3D11Resource> res;
      view->GetResource(res.put());
      const std::shared_lock lock(device_data.mutex);
      return device_data.back_buffers.contains((uint64_t)res.get());
   }

   // RT0 plus every bound PS SRV except dgVoodoo's 1x1 placeholders.
   static void LogDrawBindings(ID3D11DeviceContext* native_device_context, DeviceData& device_data, const char* what, uint32_t ps_hash)
   {
      ComPtr<ID3D11RenderTargetView> rtv;
      native_device_context->OMGetRenderTargets(1, rtv.put(), nullptr);
      char msg[512];
      std::snprintf(msg, sizeof(msg), "[Luma] ME3: %s %s PS 0x%08X -> RT0 %s%s", what, PassName(ps_hash), ps_hash, DescribeView(rtv.get()).c_str(), IsBackBuffer(device_data, rtv.get()) ? " [back buffer]" : "");
      LogLine(msg);

      ID3D11ShaderResourceView* srvs[8] = {};
      native_device_context->PSGetShaderResources(0, (UINT)std::size(srvs), srvs);
      for (UINT i = 0; i < std::size(srvs); i++)
      {
         if (!srvs[i])
            continue;
         const std::string desc = DescribeView(srvs[i]);
         srvs[i]->Release();
         if (desc.ends_with(" 1x1"))
            continue;
         std::snprintf(msg, sizeof(msg), "[Luma] ME3:    t%u %s", i, desc.c_str());
         LogLine(msg);
      }
   }

   // Rows [first_row, first_row + row_count) of a cb4 copy starting at first_row, plus the readings the shaders assume.
   static void LogCB4Rows(const char* what, uint32_t ps_hash, const float* rows, uint32_t first_row, uint32_t row_count)
   {
      char msg[256];
      for (uint32_t r = 0; r < row_count; r++)
      {
         const float* v = rows + r * 4;
         std::snprintf(msg, sizeof(msg), "[Luma] ME3: %s %s cb4[%u] = %.6f %.6f %.6f %.6f", what, PassName(ps_hash), first_row + r, v[0], v[1], v[2], v[3]);
         LogLine(msg);
      }
      // Uber and bloom-source rows always start at kCB4FirstRow (their only callers), so both readings are in range.
      const PassHashes* entry = FindPass(ps_hash);
      const Pass pass = entry ? entry->pass : Pass::None;
      if (pass == Pass::Uber)
      {
         // The output exponent (1/2.2 expected) and the output scale (the fade).
         const float* g = rows + ((IsAluUber(*entry) ? 16 : 12) - first_row) * 4;
         std::snprintf(msg, sizeof(msg), "[Luma] ME3: %s %s output scale %.4f %.4f %.4f, inverse gamma %.6f (gamma %.4f)", what, entry->name, g[0], g[1], g[2], g[3], g[3] != 0.f ? 1.f / g[3] : 0.f);
         LogLine(msg);
      }
      else if (IsBloomSource(pass))
      {
         // Bright pass, both sources: tap * saturate((max(rgb) - threshold) * 0.5), summed, * scale / 16.
         std::snprintf(msg, sizeof(msg), "[Luma] ME3: %s %s bloom scale %.6f, bright-pass threshold %.6f", what, entry->name, rows[0], rows[1]);
         LogLine(msg);
      }
   }

   // Synchronous copy + map of b4 (PS, or VS): one stall, only on request.
   static void DumpCB4Rows(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, const char* what, uint32_t ps_hash, uint32_t first_row, uint32_t row_count, bool vertex_stage = false)
   {
      ComPtr<ID3D11Buffer> cb;
      if (vertex_stage)
         native_device_context->VSGetConstantBuffers(4, 1, cb.put());
      else
         native_device_context->PSGetConstantBuffers(4, 1, cb.put());
      if (!cb)
         return;
      D3D11_BUFFER_DESC bd = {};
      cb->GetDesc(&bd);
      if (bd.ByteWidth < (first_row + row_count) * 16)
         return;
      D3D11_BUFFER_DESC sd = {};
      sd.ByteWidth = bd.ByteWidth;
      sd.Usage = D3D11_USAGE_STAGING;
      sd.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
      ComPtr<ID3D11Buffer> staging;
      if (FAILED(native_device->CreateBuffer(&sd, nullptr, staging.put())))
         return;
      native_device_context->CopyResource(staging.get(), cb.get());
      D3D11_MAPPED_SUBRESOURCE mapped = {};
      if (FAILED(native_device_context->Map(staging.get(), 0, D3D11_MAP_READ, 0, &mapped)) || mapped.pData == nullptr)
         return;
      LogCB4Rows(what, ps_hash, (const float*)mapped.pData + first_row * 4, first_row, row_count);
      native_device_context->Unmap(staging.get(), 0);
   }

   // Deferred readback: copy b4 into the tracker's ring (once per frame), map the copy from kSlots - 1 frames ago
   // without waiting, and log it when the pass or any row changed (rate-limited, a fade moves them every frame).
   static void TrackCB4Rows(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, CB4Tracker* t, const char* what, uint32_t ps_hash, uint32_t frame_index)
   {
      constexpr uint32_t kSlots = CB4Tracker::kSlots;
      ComPtr<ID3D11Buffer> cb;
      native_device_context->PSGetConstantBuffers(4, 1, cb.put());
      if (!cb)
         return;
      D3D11_BUFFER_DESC bd = {};
      cb->GetDesc(&bd);
      if (bd.ByteWidth < (kCB4FirstRow + t->row_count) * 16)
         return;
      if (t->bytes != bd.ByteWidth)
      {
         D3D11_BUFFER_DESC sd = {};
         sd.ByteWidth = bd.ByteWidth;
         sd.Usage = D3D11_USAGE_STAGING;
         sd.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
         for (auto& s : t->ring)
         {
            s.reset();
            if (FAILED(native_device->CreateBuffer(&sd, nullptr, s.put())))
            {
               for (auto& r : t->ring)
                  r.reset();
               t->bytes = 0;
               return;
            }
         }
         t->bytes = bd.ByteWidth;
         t->writes = 0;
      }

      t->ring_hash[t->writes % kSlots] = ps_hash;
      native_device_context->CopyResource(t->ring[t->writes % kSlots].get(), cb.get());
      t->writes++;
      t->copied_this_frame = true;
      if (t->writes < kSlots)
         return;

      const uint32_t oldest = t->writes % kSlots;
      D3D11_MAPPED_SUBRESOURCE mapped = {};
      if (FAILED(native_device_context->Map(t->ring[oldest].get(), 0, D3D11_MAP_READ, D3D11_MAP_FLAG_DO_NOT_WAIT, &mapped)) || mapped.pData == nullptr)
         return; // still in flight: skip this reading rather than stall
      float rows[CB4Tracker::kMaxRows][4];
      std::memcpy(rows, (const float*)mapped.pData + kCB4FirstRow * 4, t->row_count * 16);
      native_device_context->Unmap(t->ring[oldest].get(), 0);

      const uint32_t hash = t->ring_hash[oldest];
      bool changed = hash != t->logged_hash;
      // The grain perms' cb4[14] is the noise offset, re-randomized every frame: not a grade change.
      const PassHashes* entry = FindPass(hash);
      const bool has_grain = entry && std::strstr(entry->name, "Grain") && !IsAluUber(*entry); // the ALU perms keep it at cb4[18], untracked
      for (uint32_t r = 0; r < t->row_count && !changed; r++)
      {
         if (has_grain && kCB4FirstRow + r == 14)
            continue;
         for (uint32_t c = 0; c < 4 && !changed; c++)
            changed = std::abs(rows[r][c] - t->logged_rows[r][c]) > 1e-4f * (std::max)(1.f, std::abs(t->logged_rows[r][c]));
      }
      if (!changed || (hash == t->logged_hash && frame_index - t->logged_frame < kLogIntervalFrames))
         return;
      LogCB4Rows(what, hash, &rows[0][0], kCB4FirstRow, t->row_count);
      t->logged_hash = hash;
      t->logged_frame = frame_index;
      std::memcpy(t->logged_rows, rows, t->row_count * 16);
   }
#endif

   DrawOrDispatchOverrideType OnDrawOrDispatch(ID3D11Device* native_device, ID3D11DeviceContext* native_device_context, CommandListData& cmd_list_data, DeviceData& device_data, reshade::api::shader_stage stages, const ShaderHashesList<OneShaderPerPipeline>& original_shader_hashes, bool is_custom_pass, bool& updated_cbuffers, std::function<void()>* original_draw_dispatch_func) override
   {
      // Deferred contexts replay later, so anything read from or injected on one would be out of order. is_custom_pass is
      // also set on the game draws Luma replaced; only Luma's own passes have no original pixel shader.
      if (!cmd_list_data.is_primary || (is_custom_pass && original_shader_hashes.pixel_shaders[0] == SHADER_HASH_NONE))
         return DrawOrDispatchOverrideType::None;

      auto& game_device_data = GetGameDeviceData(device_data);
      const uint32_t ps_hash = original_shader_hashes.pixel_shaders[0] == SHADER_HASH_NONE ? 0u : (uint32_t)original_shader_hashes.pixel_shaders[0];
      const PassHashes* pass_entry = FindPass(ps_hash);
      const Pass pass = pass_entry ? pass_entry->pass : Pass::None;
#if DEVELOPMENT
      const uint32_t vs_hash = original_shader_hashes.vertex_shaders[0] == SHADER_HASH_NONE ? 0u : (uint32_t)original_shader_hashes.vertex_shaders[0];
      const bool on_uber_vs = std::ranges::find(kUberVSHashes, vs_hash) != std::end(kUberVSHashes);

      if (pass_entry)
      {
         bool& logged = game_device_data.pass_logged[pass_entry - kPasses];
         if (!logged)
         {
            logged = true;
            LogDrawBindings(native_device_context, device_data, "first draw", ps_hash);
         }
      }
      // A pass on the uber VS not in the table: log it once with its bindings so it can be dumped and fingerprinted.
      else if (on_uber_vs && ps_hash != 0 && game_device_data.new_uber_vs_passes_logged.insert(ps_hash).second)
      {
         LogDrawBindings(native_device_context, device_data, "NEW pass on the uber VS:", ps_hash);
      }

      // is_custom_pass is set on every draw Luma replaced (and Luma's own passes returned above): a GFx draw without it
      // is an unreplaced GFx PS.
      if (!is_custom_pass && ps_hash != 0 && std::ranges::find(kGFxVSHashes, vs_hash) != std::end(kGFxVSHashes) && game_device_data.new_gfx_passes_logged.insert(ps_hash).second)
      {
         char msg[96];
         std::snprintf(msg, sizeof(msg), "[Luma] ME3: NEW GFx PS 0x%08X on VS 0x%08X (not replaced)", ps_hash, vs_hash);
         LogLine(msg);
         LogDrawBindings(native_device_context, device_data, "NEW GFx:", ps_hash);
      }

      if (pass == Pass::Uber || IsBloomSource(pass))
      {
         const bool uber = pass == Pass::Uber;
         if (game_device_data.dump_cb_this_frame)
         {
            LogDrawBindings(native_device_context, device_data, "dump", ps_hash);
            DumpCB4Rows(native_device, native_device_context, "dump", ps_hash, kCB4FirstRow, uber ? kGradeRowCount : kBloomRowCount);
         }
         CB4Tracker& tracker = uber ? game_device_data.grade_rows : game_device_data.bloom_rows;
         if (g_track_cb_rows && !tracker.copied_this_frame)
            TrackCB4Rows(native_device, native_device_context, &tracker, uber ? "grade" : "bloom", ps_hash, game_device_data.frame_index);
      }
      // The bloom kernel: weights (PS) and tap offsets (VS) of both directions, once, or again on a frame dump.
      else if (pass == Pass::BloomFilter && (game_device_data.filter_dumps < 2 || game_device_data.dump_cb_this_frame))
      {
         const bool second = game_device_data.filter_dumps++ % 2 == 1;
         LogDrawBindings(native_device_context, device_data, second ? "filter#2" : "filter#1", ps_hash);
         DumpCB4Rows(native_device, native_device_context, second ? "filter#2 PS" : "filter#1 PS", ps_hash, kCB4FirstRow, kFilterRowCount);
         DumpCB4Rows(native_device, native_device_context, second ? "filter#2 VS" : "filter#1 VS", ps_hash, 0, kFilterVSRowCount, true);
      }

      if (g_log_frame && on_uber_vs && !game_device_data.frame_log_active)
      {
         g_log_frame = false;
         game_device_data.frame_log_active = true;
         game_device_data.frame_log_draws = 0;
         LogLine("[Luma] ME3: ---- frame log start (first uber-VS draw) ----");
      }
      if (game_device_data.frame_log_active)
      {
         ComPtr<ID3D11RenderTargetView> rtv;
         native_device_context->OMGetRenderTargets(1, rtv.put(), nullptr);
         ComPtr<ID3D11ShaderResourceView> srv0;
         native_device_context->PSGetShaderResources(0, 1, srv0.put());
         char msg[384];
         std::snprintf(msg, sizeof(msg), "[Luma] ME3: #%u %s VS 0x%08X PS 0x%08X (%s) RT0 %s%s t0 %s", game_device_data.frame_log_draws++,
            (stages & reshade::api::shader_stage::compute) != 0 ? "CS" : "draw", vs_hash, ps_hash, PassName(ps_hash), DescribeView(rtv.get()).c_str(),
            IsBackBuffer(device_data, rtv.get()) ? " [back buffer]" : "", DescribeView(srv0.get()).c_str());
         LogLine(msg);
      }

      // The final copy into the swapchain: which pass it is and what it reads.
      if (!game_device_data.swapchain_writer_logged)
      {
         ComPtr<ID3D11RenderTargetView> rtv;
         native_device_context->OMGetRenderTargets(1, rtv.put(), nullptr);
         if (IsBackBuffer(device_data, rtv.get()))
         {
            game_device_data.swapchain_writer_logged = true;
            LogDrawBindings(native_device_context, device_data, "first back-buffer write:", ps_hash);
         }
      }
#endif

      // Hide HUD: cancel every game draw into the final canvas after FXAA wrote it. Luma's own passes never reach here
      // (gate above); replaced GFx draws do, and are cancelled.
      if (g_hide_ui && game_device_data.canvas_res)
      {
         ComPtr<ID3D11RenderTargetView> rtv;
         native_device_context->OMGetRenderTargets(1, rtv.put(), nullptr);
         ComPtr<ID3D11Resource> rt;
         if (rtv)
            rtv->GetResource(rt.put());
         if (rt.get() == game_device_data.canvas_res.get())
            return DrawOrDispatchOverrideType::Replaced;
      }

#if ENABLE_BLOOM
      const bool luma_bloom = cb_luma_global_settings.GameSettings.LumaBloomEnable > 0.5f;
#endif
      if (pass == Pass::Uber)
      {
         game_device_data.srv_scene.reset();
         native_device_context->PSGetShaderResources(0, 1, game_device_data.srv_scene.put());

#if ENABLE_BLOOM
         // Pyramid off the fp16 LINEAR scene at t0, pre-glow, once per frame (ME1 2007). Karis average first: no TAA, so
         // fireflies die spatially. Core's draw helpers look their shaders up with at(): run only once all compiled.
         if (luma_bloom && !game_device_data.bloom_drawn_this_frame && game_device_data.srv_scene && FindShader(device_data.native_vertex_shaders, CompileTimeStringHash("Bloom VS")) && FindShader(device_data.native_compute_shaders, CompileTimeStringHash("Karis Average CS")) && AllShadersReady(device_data.native_pixel_shaders, {CompileTimeStringHash("Bloom Prefilter PS"), CompileTimeStringHash("Bloom Downsample PS"), CompileTimeStringHash("Bloom Upsample PS")}))
         {
            game_device_data.bloom_drawn_this_frame = true;
            // The bloom passes read BloomThreshold from LumaSettings: push it at this seam (ME1), then cache it with the rest.
            SetLumaConstantBuffers(native_device_context, cmd_list_data, device_data, reshade::api::shader_stage::pixel, LumaConstantBufferType::LumaSettings);
            DrawStateStack<DrawStateStackType::FullGraphics> bloom_state;
            bloom_state.Cache(native_device_context, device_data.uav_max_count);
            ComPtr<ID3D11ShaderResourceView> srv_karis;
            DrawKarisAverage(native_device, native_device_context, device_data, game_device_data.srv_scene.get(), srv_karis.put());
            // The sigmas are in mip texels, so nothing here is resolution-dependent.
            if (srv_karis)
               DrawBloom(native_device, native_device_context, device_data, srv_karis.get(), (int)std::size(g_bloom_sigmas), g_bloom_sigmas, game_device_data.srv_luma_bloom.put());
            bloom_state.Restore(native_device_context);
#if DEVELOPMENT
            if (!game_device_data.bloom_logged)
            {
               game_device_data.bloom_logged = true;
               char msg[256];
               std::snprintf(msg, sizeof(msg), "[Luma] ME3: Luma bloom first run: scene %s -> mip0 %s, bloom source constants %s", DescribeView(game_device_data.srv_scene.get()).c_str(), DescribeView(game_device_data.srv_luma_bloom.get()).c_str(), game_device_data.bloom_source_copied ? "copied" : "MISSING (no gather/downsample before the uber)");
               LogLine(msg);
            }
#endif
         }
         // Bound at every uber draw, nulls included: a stale slot samples garbage, a null one reads 0 (no bloom).
         ID3D11ShaderResourceView* bloom_srv = luma_bloom ? game_device_data.srv_luma_bloom.get() : nullptr;
         native_device_context->PSSetShaderResources(kLumaBloomSlot, 1, &bloom_srv);
         ID3D11SamplerState* bloom_sampler = device_data.sampler_state_linear.get();
         native_device_context->PSSetSamplers(kLumaBloomSlot, 1, &bloom_sampler);
         ID3D11Buffer* bloom_cb = game_device_data.bloom_source_copied ? game_device_data.cb_bloom_source_copy.get() : nullptr;
         native_device_context->PSSetConstantBuffers(kBloomSourceCBSlot, 1, &bloom_cb);
#endif

#if ENABLE_SMAA
         if (g_smaa_enable && g_smaa_predication)
            game_device_data.uber_constants_copied = CopyBoundPSConstants(native_device, native_device_context, std::addressof(game_device_data.cb_uber_copy));
#endif
      }

#if ENABLE_BLOOM
      // The bloom source runs before the uber: its constants carry the engine's per-volume bloom scale.
      if (luma_bloom && IsBloomSource(pass))
         game_device_data.bloom_source_copied = CopyBoundPSConstants(native_device, native_device_context, std::addressof(game_device_data.cb_bloom_source_copy));
#endif

      if (pass == Pass::Fxaa)
      {
         // FXAA writes the final canvas, the one the HUD draws on next: Hide Gameplay UI keys on it.
         ComPtr<ID3D11RenderTargetView> canvas_rtv;
         native_device_context->OMGetRenderTargets(1, canvas_rtv.put(), nullptr);
         game_device_data.canvas_res.reset();
         if (canvas_rtv)
            canvas_rtv->GetResource(game_device_data.canvas_res.put());
#if ENABLE_SMAA
         // FXAA reads the uber's canvas at t0 and writes the next canvas: SMAA takes both over and the FXAA draw is
         // skipped. Not ready or failed -> the game's FXAA runs as usual.
         if (g_smaa_enable)
         {
            ComPtr<ID3D11ShaderResourceView> input_srv;
            native_device_context->PSGetShaderResources(0, 1, input_srv.put());
            if (input_srv && canvas_rtv && RunSMAA(native_device, native_device_context, device_data, game_device_data, input_srv.get(), canvas_rtv.get()))
               return DrawOrDispatchOverrideType::Replaced;
         }
#endif
      }

      // Blend repair LAST: it re-issues the draw, so it must yield to every hook above (it disabled one in TW2).
      if (FixImpossiblePerRTBlend(native_device, native_device_context, game_device_data, stages, original_shader_hashes, is_custom_pass, original_draw_dispatch_func))
         return DrawOrDispatchOverrideType::Replaced;

      return DrawOrDispatchOverrideType::None;
   }

   void OnPresent(ID3D11Device* native_device, DeviceData& device_data) override
   {
      auto& game_device_data = GetGameDeviceData(device_data);
      // Per-frame captures, and address space back when a feature is off. On the render thread, never mid-frame.
      game_device_data.srv_scene.reset();
      game_device_data.canvas_res.reset();
#if ENABLE_BLOOM
      game_device_data.srv_luma_bloom.reset();
      game_device_data.bloom_source_copied = false;
      game_device_data.bloom_drawn_this_frame = false;
      // Core's DrawKarisAverage output is ~66 MB at 4K and core drops only its UAV on swapchain init: both views go here.
      // Unconditional while off (ME1): resetting empty entries is a few lookups.
      if (cb_luma_global_settings.GameSettings.LumaBloomEnable <= 0.5f)
      {
         auto& mr = device_data.managed_resources;
         mr.unordered_access_views[CompileTimeStringHash("luma_karis_average")].reset();
         mr.shader_resource_views[CompileTimeStringHash("luma_karis_average")].reset();
         game_device_data.cb_bloom_source_copy.reset();
      }
#endif
#if ENABLE_SMAA
      game_device_data.uber_constants_copied = false;
      if (!g_smaa_enable && game_device_data.tex_input_linear)
      {
         game_device_data.ReleaseSMAAScratch();
         game_device_data.cb_uber_copy.reset();
         ReleaseCoreSMAAIntermediates(device_data);
         game_device_data.smaa_w = game_device_data.smaa_h = 0; // core recreates lazily; keep the latch honest
      }
      else
      {
         if (!g_smaa_predication && game_device_data.tex_pred)
            game_device_data.ReleasePredicationScratch();
         if (g_rcas_sharpness <= 0.f && game_device_data.tex_smaa_out)
            game_device_data.ReleaseSharpenScratch();
      }
#endif
#if DEVELOPMENT
      game_device_data.grade_rows.copied_this_frame = false;
      game_device_data.bloom_rows.copied_this_frame = false;
      game_device_data.dump_cb_this_frame = std::exchange(g_dump_cb, false);
      game_device_data.frame_index++;
      if (game_device_data.frame_log_active)
      {
         game_device_data.frame_log_active = false;
         LogLine("[Luma] ME3: ---- frame log end (present) ----");
      }
#endif
   }

   void PrintImGuiAbout() override
   {
      ImGui::PushTextWrapPos(0.f);
      ImGui::Text(
         "Luma for \"Mass Effect 3\" (2012) is developed by DristoforColumb and is open source and free.\n"
         "It adds HDR, HDR bloom, SMAA anti-aliasing, and 16x anisotropic filtering.\n"
         "It runs through dgVoodoo2 (DirectX 9 -> 11).\n"
         "Do NOT run another HDR mod (e.g. RenoDX) alongside it.\n"
         "Thanks to the Luma team and contributors.\n"
         "If you enjoy it, consider donating.");
      ImGui::PopTextWrapPos();

      ImGui::NewLine();
      ImGui::PushStyleColor(ImGuiCol_Button, IM_COL32(70, 134, 0, 255));
      ImGui::PushStyleColor(ImGuiCol_ButtonHovered, IM_COL32(70 + 9, 134 + 9, 0, 255));
      ImGui::PushStyleColor(ImGuiCol_ButtonActive, IM_COL32(70 + 18, 134 + 18, 0, 255));
      static const std::string donation_link = std::string("Buy DristoforColumb a Coffee on ko-fi ") + std::string(ICON_FK_OK);
      if (ImGui::Button(donation_link.c_str()))
         ShellExecuteA(nullptr, "open", "https://ko-fi.com/dristoforcolumb", nullptr, nullptr, SW_SHOWNORMAL);
      ImGui::PopStyleColor(3);

      ImGui::NewLine();
      static const std::string social_link = std::string("Join our \"HDR Den\" Discord ") + std::string(ICON_FK_SEARCH);
      if (ImGui::Button(social_link.c_str()))
      {
         // Unique link for Luma's HDR Den (tracks the origin of people joining); do not share for other purposes.
         static const std::string discord_link = std::string("https://discord.gg/J9fM") + std::string("3EVuEZ");
         ShellExecuteA(nullptr, "open", discord_link.c_str(), nullptr, nullptr, SW_SHOWNORMAL);
      }
      static const std::string contributing_link = std::string("Contribute on Github ") + std::string(ICON_FK_FILE_CODE);
      if (ImGui::Button(contributing_link.c_str()))
         ShellExecuteA(nullptr, "open", "https://github.com/Filoppi/Luma-Framework", nullptr, nullptr, SW_SHOWNORMAL);

      ImGui::NewLine();
      ImGui::Text("Build Date: %s %s", __DATE__, __TIME__);

      ImGui::NewLine();
      ImGui::Text("Credits:"
                  "\n\nMain:"
                  "\nDristoforColumb"
                  "\n\nThird Party:"
                  "\nReShade"
                  "\nImGui"
                  "\nRenoDX (HDR tonemap method)"
                  "\nDICE (HDR tonemapper)"
                  "\nMacLeod-Boynton hue emulation (RenoDX)"
                  "\nSMAA (Iryoku)"
                  "\nAMD FidelityFX (RCAS)"
                  "\ndgVoodoo2 by Dege (DirectX 9 -> 11 wrapper, required)");
   }
};

BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
{
   if (ul_reason_for_call == DLL_PROCESS_ATTACH)
   {
      const char* project_name = PROJECT_NAME;
      const char* cleared_project_name = (project_name[0] == '_') ? (project_name + 1) : project_name;

      uint32_t mod_version = 1;
      // The website MUST be "" and never nullptr: SetGlobals strncpy's it, and a null AVs in ucrtbase during
      // DllMain, which ReShade reports as addon load error 1114.
      Globals::SetGlobals(cleared_project_name, "Mass Effect 3 (2012) Luma mod", "", mod_version);

      swapchain_format_upgrade_type = TextureFormatUpgradesType::AllowedEnabled;
      swapchain_upgrade_type = SwapchainUpgradeType::scRGB;
      // The in-game brightness slider is a D3D9 SetGammaRamp that dgVoodoo forwards to the OS device ramp, which
      // would distort the scRGB output. This only exposes core's "Reset Gamma Ramp" button.
      allow_disabling_gamma_ramp = true;

      // Two HDR-clipping families, upgraded INDIRECTLY: changing a dgVoodoo resource's creation format black-screens the
      // game (ME1/ME2/MEA). Measured formats: the three 4K canvases (uber target, FXAA input, final canvas) are
      // r8g8b8a8_typeless, the DoF/bloom gather r16g16b16a16_typeless viewed unorm. The 4K 8-bit velocity buffer
      // matches the first rule too; harmless, but it costs address space in this 32-bit process.
      texture_format_upgrades_type = TextureFormatUpgradesType::AllowedEnabled;
      enable_indirect_texture_format_upgrades = true;
      enable_chain_indirect_texture_format_upgrades = ChainTextureFormatUpgradesType::DirectDependencies;
      texture_upgrade_formats = {
         reshade::api::format::r8g8b8a8_typeless,
         reshade::api::format::r16g16b16a16_typeless,
      };
      // "No1Px" is mandatory under dgVoodoo: 1x1 placeholders fill every unused slot and pass the aspect filter.
      texture_format_upgrades_2d_size_filters = (uint32_t)TextureFormatUpgrades2DSizeFilters::SwapchainResolution | (uint32_t)TextureFormatUpgrades2DSizeFilters::SwapchainAspectRatio | (uint32_t)TextureFormatUpgrades2DSizeFilters::No1Px;

      // AF16x. force_upgrade_linear_samplers is load-bearing: dgVoodoo binds no ANISOTROPIC samplers, so mode 4 alone is
      // a no-op (ME1/ME2/TW2). LOD bias stays 0: no temporal AA here. Boot-time only.
      enable_samplers_upgrade = true;
      samplers_upgrade_mode = 4;
      force_upgrade_linear_samplers = true;

#if DEVELOPMENT
      for (const auto& entry : kPasses)
      {
         forced_shader_names.emplace(entry.hash, entry.name);
         forced_shader_names.emplace(entry.hash_v281, entry.name);
      }
#endif

      game = new MassEffect3Game();
   }

   CoreMain(hModule, ul_reason_for_call, lpReserved);

   return TRUE;
}
