// The reactive mask for FSR and Luma TAA, autogenerated (FSR-Best-Practices FMSK-8) because the materials are loaded from the archives
// at runtime, which leaves no per-draw hook. It compares the scene before the transparent phase with the scene SR reads. main.cpp
// copies the former right after PS_OcclCoverDropouts, or at the mid-forward PS_Tex as a fallback. What changes in between is mostly
// translucents, particles and VFX without motion vectors.
// Both are exposed by the game's auto exposure (the tonemap's g_AdaptedLumBuffer[1], last frame's multiplier) and tonemapped with
// x / (1 + x). As in AMD's generator, the max channel difference is then multiplied by the scale (CustomData3). With a threshold
// (CustomData4) the mask is 0 under it and 0.9 over it. At 0, it's the scaled difference capped at 0.9 (FMSK-4).

#include "Includes/Common.hlsl"

Texture2D<float3> opaqueScene : register(t0);
Texture2D<float3> finalScene : register(t1);
StructuredBuffer<float> exposureBuffer : register(t2); // g_AdaptedLumBuffer
RWTexture2D<float> reactive : register(u0);

[numthreads(8, 8, 1)] void main(uint3 id : SV_DispatchThreadID) {
   uint elements, stride;
   exposureBuffer.GetDimensions(elements, stride);
   const float exposure = (elements > 1 ? exposureBuffer[1] : 1.0);
   const float3 opaque = opaqueScene.Load(int3(id.xy, 0)) * exposure;
   const float3 final = finalScene.Load(int3(id.xy, 0)) * exposure;
   const float difference = max3(abs(final / (1.0 + final) - opaque / (1.0 + opaque))) * LumaData.CustomData3;
   const float threshold = LumaData.CustomData4;
   reactive[id.xy] = (threshold > 0.0 ? (difference < threshold ? 0.0 : 0.9) : min(difference, 0.9));
}
