# Generates csmt_methods.h (vtable slot lists of the D3D9 interfaces the CSMT layer patches) from the Windows SDK's
# d3d9.h, where every interface redeclares its inherited methods in vtable order.
#   python gen_csmt_methods.py [path\to\d3d9.h]
import glob, os, re, sys

INTERFACES = [
   ('DEVICE', 'IDirect3DDevice9Ex'),
   ('SWAP_CHAIN', 'IDirect3DSwapChain9Ex'),
   ('STATE_BLOCK', 'IDirect3DStateBlock9'),
   ('VERTEX_DECLARATION', 'IDirect3DVertexDeclaration9'),
   ('VERTEX_SHADER', 'IDirect3DVertexShader9'),
   ('PIXEL_SHADER', 'IDirect3DPixelShader9'),
   ('TEXTURE', 'IDirect3DTexture9'),
   ('VOLUME_TEXTURE', 'IDirect3DVolumeTexture9'),
   ('CUBE_TEXTURE', 'IDirect3DCubeTexture9'),
   ('VERTEX_BUFFER', 'IDirect3DVertexBuffer9'),
   ('INDEX_BUFFER', 'IDirect3DIndexBuffer9'),
   ('SURFACE', 'IDirect3DSurface9'),
   ('VOLUME', 'IDirect3DVolume9'),
   ('QUERY', 'IDirect3DQuery9'),
]

header = sys.argv[1] if len(sys.argv) > 1 else sorted(
   glob.glob(r'C:\Program Files (x86)\Windows Kits\10\Include\*\shared\d3d9.h'))[-1]
text = open(header, encoding='latin-1').read()
out = ['// Generated by gen_csmt_methods.py from the Windows SDK d3d9.h; do not edit.',
   '// CSMT_<KIND>(X): X(KIND, interface, method, vtable slot) for every slot, in vtable order.', '#pragma once', '']
for kind, name in INTERFACES:
   body = re.search(r'DECLARE_INTERFACE_\(' + name + r',.*?\n\{(.*?)\n\};', text, re.S).group(1)
   methods = re.findall(r'STDMETHOD_?\((?:[^,()]+,\s*)?(\w+)\)', body)
   out.append(f'#define CSMT_{kind}(X) \\')
   out += [f'   X({kind}, {name}, {method}, {slot}) \\' for slot, method in enumerate(methods)]
   out.append('')
   out.append(f'constexpr int CSMT_{kind}_SLOTS = {len(methods)};')
   out += [f'constexpr int CSMT_SLOT_{kind}_{method} = {slot};' for slot, method in enumerate(methods)]
   out.append('')
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'csmt_methods.h')
open(path, 'w', newline='\r\n').write('\n'.join(out))
print(path, {kind: len(re.findall(r'STDMETHOD', re.search(r'DECLARE_INTERFACE_\(' + name + r',.*?\n\{(.*?)\n\};', text, re.S).group(1))) for kind, name in INTERFACES})
